# Book settings
title: pyDocking
author: Tuhin
logo: docs/images/logo.png

repository:
  url: https://github.com/tuhinmallick/pyDocking
  branch: main

html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://tuhinmallick.github.io/pyDocking

only_build_toc_files: true
